<?php

// echo("<h2 id='resultat'><br/></h2>
//
//     <div id='imagesuser'>
//         <a href='javascript:chifoumideuxjoueurs('pierre',0);''><img src='img/pierre.jpg' alt='pierre' id='pierre'></a>
//         <a href='javascript:chifoumideuxjoueurs('feuille',0);''><img src='img/feuille2.jpg' alt='feuille' id='feuille'></a>
//         <a href='javascript:chifoumideuxjoueurs('ciseaux',0);''><img src='img/ciseaux2.jpg' alt='ciseaux' id='ciseaux'></a>
//         <a href='javascript:chifoumideuxjoueurs('puits',0);''><img src='img/puits2.jpg' alt='puits' id='puits'></a>
//     </div>
//
//     <div class='score'>
//     <h2 id='scoreusertitre'>Joueur 1 : <span id='scoreuser'>0</span></h2><h2 id='scorejoueur2titre'>   -   <span id='scorejoueur2'>0</span> : Joueur 2</h2>
//     </div>
//
//     <div id='imagesjoueur2'>
//         <a href='javascript:chifoumideuxjoueurs(0,'pierre');''><img src='img/pierre.jpg' alt='pierre' id='pierrejoueur2'></a>
//         <a href='javascript:chifoumideuxjoueurs(0,'feuille');''><img src='img/feuille2.jpg' alt='feuille' id='feuillejoueur2'></a>
//         <a href='javascript:chifoumideuxjoueurs(0,'ciseaux');''><img src='img/ciseaux2.jpg' alt='ciseaux' id='ciseauxjoueur2'></a>
//         <a href='javascript:chifoumideuxjoueurs(0,'puits');''><img src='img/puits2.jpg' alt='puits' id='puitsjoueur2'></a>
//     </div>
// ");
